using System;

namespace HashTableDemo
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("Hello Welcome to HashTables.");
            string paragraph = "To be or not to be";
            ///Split method returns an array of strings generated by splitting of original string.
            string[] para = paragraph.Split(" ");
            ///Creating reference of MyMapNode.
            MyMapNode<int, string> hash = new MyMapNode<int, string>(para.Length);
            int key = 0;
            ///foreach iterates on paragraph and adds key and value to hash.
            foreach (string word in para)
            {
                hash.Add(key, word);
                key++;
            }
            Console.WriteLine("Frequency :" + hash.GetFrequency("be"));
        }
    }
}
